### ISSUE TITLE
model-value doesn't work in VRadioGroup

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#103]
### Environment

"@gits-id/ui-nuxt": "^0.14.3"
"vee-validate": "^4.0.0"

### Reproduction

https://stackblitz.com/edit/github-ycbgbo?file=app.vue

### Describe the bug

hi @gravitano,

first, thank your for update. i have already update version. Vselect works fine now.

and i found bug when using VRadioGroup Component
model-value doesn't work. selected item doesn't set and not highlighted.

here is my code :
`
        <VRadioGroup
          name="gender"
          label="Gender"
          placeholder="Choose"
          :items="gender"
          :model-value="dataGenderDB"
        />
`

**Comment by gravitano** [comment]
Hi @karis, I just released a new version `0.14.4`, which includes fixing this issue. Could you try updating and report back if anything breaks?

**Comment by karis** [comment]
hi @gravitano 
absolutely yes,
