### ISSUE TITLE
Date with range option

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#108]
### Describe the feature

request range selection.
with actual range options.
User can choose start date and end date.
returned 2 variables as start and end of the selected date

This date range feature is often used in report forms.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the contribution guide.
- [X] Check existing discussions and [issues](https://github.com/gitsindonesia/ui-component/issues).

**Comment by gravitano** [comment]
Hi @karis,

Thanks for the request. Currently, we don't have the plan to create our own custom library for handling DatePicker or Calendar. But, you use the popular existing library out there like [VCalendar](https://vcalendar.io/) or [Vue3DatePicker](https://vue3datepicker.com/) which have a date range feature as you requested.
