### ISSUE TITLE
 Failed to resolve component: VStepper 

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#124]
### Environment

  "dependencies": {
    "@gits-id/ui-nuxt": "^0.16.3",
    "@nuxt/vite-builder": "^3.2.0"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.3.1",
    "nuxt": "3.2.0",
    "sass": "^1.58.0"
  }

### Reproduction

https://stackblitz.com/edit/github-ycbgbo-uckjpm

### Describe the bug

hi @gravitano 

can you check this feature, VStepper not shown in latest version.

**Comment by gravitano** [comment]
Strange. It should be registered by default. For now, it needs to be installed manually.

```bash
yarn add @gits-id/stepper
```

Use it like so:
```vue
<script setup lang="ts">
import VStepper from '@gits-id/stepper';
import '@gits-id/stepper/dist/style.css';
</script>

<template>
  <VStepper />
</template>
```

Check the forked version: https://stackblitz.com/edit/github-ycbgbo-yifogh?file=app.vue

**Comment by karis** [comment]
thx @gravitano,

i'll use this solution.
