### ISSUE TITLE
cannot disable radio button

### ISSUE THREAD

**Issue by gits-gretchelin** [gitsindonesia/ui-component#13]
I noticed that passing `disabled` prop in `VRadio`  doesn't make the input disabled. After reading the source code, there is no `disabled` prop in the component, and the only to prop being passes to actual input aside from value is just styling classes.

```
<input
        :id="id"
        v-model="inputValue"
        type="radio"
        :name="name"
        :value="value"
        class="transition duration-300"
        :class="[inputClass, colorClass]"
      />
```

https://github.com/gitsindonesia/ui-component/blob/15f681a7daa0821122b6bcb8f9cabb1f24d9997e/packages/forms/src/radio/VRadio.vue#L110

**Comment by gravitano** [comment]
Thanks for the report. Noted for now.
