### ISSUE TITLE
yarn add @morpheme/ui-nuxt not found

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#174]
### Environment

here is my package.json

` "devDependencies": {
    "@nuxtjs/eslint-module": "^4.0.2",
    "@nuxtjs/tailwindcss": "^6.6.8",
    "@tailwindcss/typography": "^0.5.9",
    "@types/node": "^18",
    "nuxt": "^3.4.3",
    "prettier": "^2.8.8",
    "tailwindcss": "^3.3.2",
    "vitest": "^0.31.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.10",
    "@vueuse/nuxt": "^10.1.2",
    "pinia": "^2.0.36"
  }`

### Reproduction

i just create from scratch then add package in Environment

### Describe the bug

when i want to add morpheme/ui-nuxt
it print logs like below.

<img width="757" alt="Screenshot 2023-05-11 at 14 55 30" src="https://github.com/gitsindonesia/ui-component/assets/1776951/1c417b14-53d3-45c5-87c6-a3866a426800">

### Logs

```shell
yarn add v1.22.19
warning ../../../../package.json: No license field
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@morpheme%2fui-nuxt: Not found".
info If you think this is a bug, please open a bug report with the information provided
```

**Comment by gravitano** [comment]
Hi, it is renamed to `@morpheme/nuxt` since Beta 5. Check out migration guide here: https://gitsindonesia.github.io/ui-component/guide/migration.html#from-gits-ui-to-morpheme-ui-1-0-0-beta-5

**Comment by karis** [comment]
hi @gravitano 
yes..
i just found that the documentation need to be update..

 thank you..
