### ISSUE TITLE
css not loaded when fresh build from starter kit

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#179]
### Environment

Nuxt project info: (copied to clipboard)                                                                                                            10:12:30 AM

------------------------------
- Operating System: Darwin
- Node Version:     v18.12.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.4.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, typescript, morpheme, devtools, css, colorMode, vite, experimental
- Runtime Modules:  @morpheme/nuxt@1.0.0-beta.11, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/color-mode@3.3.0
- Build Modules:    -
------------------------------

### Reproduction

Source download from [stackblitz-kitchen-sink](https://stackblitz.com/github/gitsindonesia/ui-component/tree/main/starter/kitchen-sink)

### Describe the bug

hi @gravitano ,

i was download from [stackblitz-kitchen-sink](https://stackblitz.com/github/gitsindonesia/ui-component/tree/main/starter/kitchen-sink)

i test in my environment, using node 18.9.2

after build and run, below is my result.

<img width="1496" alt="Screenshot 2023-08-08 at 10 05 18" src="https://github.com/gitsindonesia/ui-component/assets/1776951/4d5a4f06-fc62-4a00-bf41-af62e1ff3d8c">
<img width="1512" alt="Screenshot 2023-08-08 at 10 05 24" src="https://github.com/gitsindonesia/ui-component/assets/1776951/d76e6acc-206b-4d51-b73e-563066536f4b">

i already check in migration documentation. but still no clue..
please help me,

thanks

karis

**Comment by gravitano** [comment]
It's working fine here: https://stackblitz.com/github/gitsindonesia/ui-component/tree/main/starter/kitchen-sink

Try using Node 16 and PNPM.

**Comment by karis** [comment]
<img width="1512" alt="Screenshot 2023-08-08 at 21 35 07" src="https://github.com/gitsindonesia/ui-component/assets/1776951/6508889b-e810-4ff3-9439-31b2b9bdf409">

i already test using node 16 and pnpm

it still the same..

**Comment by gravitano** [comment]
Idk what wrong. But, it's working fine on Stackblitz.

Have you tried using Morpheme CLI and use other template?

**Comment by karis** [comment]
I have tried morpheme cli
Last night i also build from nuxt then i install morpheme. The result is
same..

**Comment by karis** [comment]
<img width="976" alt="Screenshot 2023-08-10 at 09 52 01" src="https://github.com/gitsindonesia/ui-component/assets/1776951/80e6fba5-d016-4b02-8491-86db0dfff4b2">

any clues? may be  i miss something while downloading the module or else?

**Comment by karis** [comment]
im doing dumb test..

i change `morpheme: {` in nuxt.config.ts into 'gitsUi :{'
and this what is happen..

<img width="1512" alt="Screenshot 2023-08-10 at 13 45 17" src="https://github.com/gitsindonesia/ui-component/assets/1776951/fb518eeb-50a3-4fed-b2e4-77f354a22b48">

**Comment by gravitano** [comment]
Try [this](https://github.com/gravitano/morpheme-kitchen-sink-example). It's fresh from CLI. Should be okay.

**Comment by karis** [comment]
hi @gravitano 

sorry for late response,

i already update to rc1

and im still stuck in this setting

`
  gitsUi: {
    theme: 'morpheme',
    sass: true,
    darkMode: false,
    optimizeDeps: false,
    transpileDeps: false,
  },
`

because 
`morpheme :{ ___ } 
`
doesnt work

i dont have any idea yet.

**Comment by karis** [comment]
hai @gravitano 

alhamdulillah

solved by 

checkout your new kitchen sink from stackblitz

and 
`pnpm update `

then i migrate several code from last project..


thanks alot
