### ISSUE TITLE
custom css for datatable per row

### ISSUE THREAD

**Issue by Alirexaa** [gitsindonesia/ui-component#184]
### Describe the feature

It's good to add some slots for customizing data table rows.

for example, change the row background color conditionally per row.

example :
a data table that contains server logs.
we have three types of log records: Information, Warning, and Error.
for Information rows background-color: light
for warning rows background-color: yellow
for error rows background-color:  red

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the contribution guide.
- [X] Check existing discussions and [issues](https://github.com/gitsindonesia/ui-component/issues).

**Comment by gravitano** [comment]
Hi @Alirexaa, thanks for the suggestion. Do you have any examples/preferences? I think I could add this in the next release.

**Comment by kisharnath** [comment]
Can I work on this?

**Comment by gravitano** [comment]
@kisharnath Yes. PR is welcome.

**Comment by gravitano** [comment]
Hi @Alirexaa, can you check #188. Is it enough?

**Comment by Alirexaa** [comment]
> Hi @Alirexaa, can you check #188. Is it enough?

It seems Ok. i should test it in my project

**Comment by gravitano** [comment]
@Alirexaa: It's released on a new [RC.3](https://github.com/gitsindonesia/ui-component/releases/tag/v1.0.0-rc.3). Please try and let me know if there are any problems.
