### ISSUE TITLE
Injection "Symbol(VBadge)" not found. 

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#186]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.8.1`
- Nuxt Version:     `3.7.4`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `pnpm@8.9.1`
- Builder:          `-`
- User Config:      `modules`, `auth`, `typescript`, `gtag`, `morpheme`, `devtools`, `css`, `imports`, `colorMode`, `vite`, `experimental`, `tailwindcss`, `build`
- Runtime Modules:  `@morpheme/nuxt@1.0.0-rc.2`, `@nuxtjs/tailwindcss@6.8.0`, `@nuxtjs/color-mode@3.3.0`, `@sidebase/nuxt-auth@0.5.0`, `@vueuse/nuxt@10.5.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/gitsindonesia-ui-component-ac3exz?file=pages%2Findex.vue

![Screenshot 2023-10-17 at 18 01 12](https://github.com/gitsindonesia/ui-component/assets/1776951/fbe18131-f6a9-4b6c-a02f-3667c1542508)

### Describe the bug

hi @gravitano ,
its a minor bug,  

when tester check on CHROME Inspect.
it was print 

```
[Vue warn]: injection "Symbol(VBadge)" not found. 
  at <VBadge class="w-fit" color="primary" small="" > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="nav-drawer-right-transition" > 
```

### Logs

```shell
[Vue warn]: injection "Symbol(VBadge)" not found. 
  at <VBadge class="w-fit" color="primary" small="" > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="nav-drawer-right-transition" >
```

**Comment by gravitano** [comment]
You can ignore it is just warning. Re-open if this issue breaking your app.
