### ISSUE TITLE
VLogo does not provide an export named 'Sizes'

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#190]
### Environment

https://stackblitz.com/edit/gitsindonesia-ui-component-8fbfma?file=nuxt.config.ts

### Reproduction

https://stackblitz.com/edit/gitsindonesia-ui-component-8fbfma?file=nuxt.config.ts

### Describe the bug

vue.js?v=303e5832' does not provide an export named 'PropType'

Inspect Browser then, see console error

`does not provide an export named 'Sizes' (at VLogo.vue:3:9)`

### Logs

```shell
VLogo.vue:3 Uncaught (in promise) SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@morpheme+logo@1.0.0-rc.4_typescript@5.2.2/node_modules/@morpheme/logo/src/types.ts?v=7ae9a6c8' does not provide an export named 'Sizes' (at VLogo.vue:3:9)
```

**Comment by gravitano** [comment]
Fixed on RC.5. Please try and report if there are problems.

**Comment by karis** [comment]
hi @gravitano 

i already download kitchen-sink new update
and i still found similiar error, now it prints
`does not provide an export named 'PropType'`

then icheck on console. like below..

![Screenshot 2023-11-11 at 18 22 57](https://github.com/gitsindonesia/ui-component/assets/1776951/59c70898-709a-4f2d-b8ef-66cacd76c72d)


![Screenshot 2023-11-11 at 18 21 49](https://github.com/gitsindonesia/ui-component/assets/1776951/03c1c871-7d03-406f-9ab6-0f7e88e0a614)


can you explain why this error show up?

**Comment by karis** [comment]
hi @gravitano 

i think it was the solution;
BEFORE :::


![Screenshot 2023-11-11 at 18 33 56](https://github.com/gitsindonesia/ui-component/assets/1776951/0e6219be-7aed-4960-85f7-faeb8fb897e2)

AFTER ::::
![Screenshot 2023-11-11 at 18 33 33](https://github.com/gitsindonesia/ui-component/assets/1776951/9e3779b8-d485-44e6-b265-a227ef7a0d1f)

Check line 2 and 3...

thankyou

**Comment by karis** [comment]
thanks mas @gravitano 

it works for the update..

then i check. scenario form logout - to register..

i found
![Screenshot 2023-11-12 at 23 43 23](https://github.com/gitsindonesia/ui-component/assets/1776951/3cb3a1ea-ef6d-4fb0-83c2-45a6dc04e05b)


it also appears on

[stackblitz login](https://stackblitz.com/edit/gitsindonesia-ui-component-xkoz2e?file=package.json
)

best regard

karis

**Comment by karis** [comment]
hi @gravitano 

here is new listing


FieldOptions not found in VSelect.vue

i dont check on Stackblitz yet. but i think it would be the same.

![Screenshot 2023-11-13 at 08 27 05](https://github.com/gitsindonesia/ui-component/assets/1776951/167f8ff5-1a90-4a07-b7a0-2ddf48e3a8e1)


thank you,

**Comment by gravitano** [comment]
It's fixed on RC.7. Please try and report back. Thanks!

**Comment by karis** [comment]
yes...i already update
problem solved

then
 
i found. VCheckbox only showing the label...
and when start up the project,

Printed error below
`
 WARN  Failed to load Tailwind config at: ./tailwind.config.js Cannot find module 'lodash.merge'                        nuxt:tailwindcss 6:29:00 PM
Require stack:
- /Users/karismaji/Development/Project/Sumowono/ClinicDigital/omniclinic-id/node_modules/.pnpm/@morpheme+tailwind-config@1.0.0-rc.4_typescript@4.9.5/node_modules/@morpheme/tailwind-config/preset.js

  Require stack:
  - node_modules/.pnpm/@morpheme+tailwind-config@1.0.0-rc.4_typescript@4.9.5/node_modules/@morpheme/tailwind-config/preset.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
  at Function.resolve (node:internal/modules/helpers:187:19)
  at _resolve (node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:251148)
  at jiti (node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:253746)
  at node_modules/.pnpm/@morpheme+tailwind-config@1.0.0-rc.4_typescript@4.9.5/node_modules/@morpheme/tailwind-config/preset.js:3:15
  at evalModule (node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254371)
  at tailwind.config.js:10:13
  at evalModule (node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254371)
`
