### ISSUE TITLE
FileList is not defined

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#193]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.5.0`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `nitro`, `modules`, `auth`, `typescript`, `morpheme`, `devtools`, `css`, `imports`, `colorMode`, `vite`, `experimental`, `tailwindcss`
- Runtime Modules:  `@morpheme/nuxt@1.0.0-rc.7`, `@nuxtjs/tailwindcss@6.10.1`, `@nuxtjs/color-mode@3.3.2`, `@sidebase/nuxt-auth@0.6.3`, `@vueuse/nuxt@10.7.0`, `nuxt-gtag@1.1.2`
- Build Modules:    `-`

### Reproduction

```
<script setup lang="ts">
const logo = ref()

const onChange = (val: any) => {
  console.log(val);
};
</script>

<template>
    <div>
        <span class="block text-2xl my-4 font-light">Organizations Details</span>

        <span class="block text-xs my-1 font-light">Organization's logo</span>
        <NuxtImg v-if="logo" :src="logo"/>
        <VFileUpload v-else  v-model="logo" name="group-logo" theme="dropzone" rounded image 
        @update:modelValue="onChange" />
        <span class="block text-xs my-1 font-light">Maximum 4MB. File Format (png, jpg, svg) </span>
    </div>
</template>
```

### Describe the bug

hi @gravitano ,

I just want to detailing my Organization form by adding VFileUpload, to update Organization logo.
then i just got error FileList is not defined

do i have to import the types? or will you create a patch?

thanks

**Comment by gravitano** [comment]
Try wrapping with `<ClientOnly>` component:

```vue
<script setup lang="ts">
const logo = ref()

const onChange = (val: any) => {
  console.log(val);
};
</script>
<template>
    <div>
        <span class="block text-2xl my-4 font-light">Organizations Details</span>

        <span class="block text-xs my-1 font-light">Organization's logo</span>
        <NuxtImg v-if="logo" :src="logo"/>

        <ClientOnly>
<VFileUpload v-else  v-model="logo" name="group-logo" theme="dropzone" rounded image 
        @update:modelValue="onChange" />
</ClientOnly>

        <span class="block text-xs my-1 font-light">Maximum 4MB. File Format (png, jpg, svg) </span>
    </div>
</template>
```

**Comment by gravitano** [comment]
Or try using the new `FileInput` component https://ui.morpheme.design/forms/file-input.html

**Comment by karis** [comment]
oke thankyou, 

it works using <ClientOnly />
