### ISSUE TITLE
Add `autoResize` Prop to `VTextarea` Component

### ISSUE THREAD

**Issue by rizkysafdila** [gitsindonesia/ui-component#198]
**Description:**
I would like to request the addition of an `autoResize` prop to the `VTextarea` component in the Morpheme UI library. This prop would enable the textarea to automatically resize vertically based on the content, improving user experience by eliminating the need for manual resizing.

**Use Case:**
The `autoResize` prop is valuable in scenarios where the content length varies significantly, such as:
- **Forms and Surveys**: Users can write responses of varying lengths without being constrained by a fixed textarea size, ensuring all text is visible without scrolling.
- **Chat Applications**: Messages can expand naturally, accommodating short and long texts alike without excess space.
- **Content Management Systems**: Writers can see their full text as they type, enhancing readability and ease of use.

Currently, developers have to implement custom JavaScript or CSS to achieve this functionality, which can be cumbersome and inconsistent across projects. Integrating `autoResize` directly into the `VTextarea` component would streamline development and improve the component's usability.

**Example Implementation:**
Here's an example of how the `autoResize` prop could be utilized in a Vue component:

```vue
<template>
  <VTextarea
    v-model="message"
    autoResize
    label="Message"
    placeholder="Type your message here..."
  />
</template>

**Comment by gravitano** [comment]
Hi, thanks for the request. Unfortunately, currently we focus on stabilization and preparation for releasing `v1`. In the meantime, You can use `useTextareaAutosize` from `@vueuse` [https://vueuse.org/core/useTextareaAutosize/](https://vueuse.org/core/useTextareaAutosize/) as the alternative. Or maybe integrating it with `VTextarea`.
