### ISSUE TITLE
[DataTatablePagination] Customizable info text

### ISSUE THREAD

**Issue by gits-gretchelin** [gitsindonesia/ui-component#2]
I noticed that text info settings are 'locked' to a certain format as in: 
`{showing_text} xx-xx {from_text} xxx ${data_text}`

Considering not all language are formatted the same way and some design may required more *customized* text that may require some of the value omitted, for example: `[itemsPerPageInput] from 40 datas.`. It may be more flexible to give, for example, an `infoText` prop which expects a string or a callback like below so user can customize their texts as their wish.

```
<v-data-table-pagination
    :info-text="(currentPage, itemsPerPage, totalItems) => { return "whatever string here"; }"
/>
```

Also, ability to show or hide the info text or any particular "content" of the pagination would be greatly appreciated! Sometimes, we don't need those info text, or ability to change `itemsPerPage` after all.

```
// package.json

"@gits-id/ui": "^0.10.12",
```

**Comment by gravitano** [comment]
Thanks for the feedback. Maybe we will add slots for custom text. PR is welcome.

**Comment by gravitano** [comment]
Done in `@gits-id/ui@0.11.4`. 

Checkout example here: https://gits-ui.web.app/?path=/story/components-datatablepagination--meta-slot
