### ISSUE TITLE
[DataTatablePagination] class props value bleeds into wrapper div

### ISSUE THREAD

**Issue by gits-gretchelin** [gitsindonesia/ui-component#3]
I'm trying to customize the styling of the `v-data-table-pagination` nav wrapper, but I noticed that the `class` prop value was applied at two placed. In the image I attached, `THIS_SHOULD_NOT_BLEED` value is being applied both at the container (a `div`) and the actual pagination container (a `nav`) when I use the component like this:

```
<v-data-table-pagination 
          class="styled-pagination THIS__SHOULD__NOT__BLEED"
          v-model:modelValue="page"
          v-model:items-per-page="itemsPerPage"
         active-class="activeClass__ bg-secondary-500 text-white hover:bg-secondary-500 rounded-full border-0"
 />
```

![image](https://user-images.githubusercontent.com/101326799/188084621-58f64d4c-940f-4a6d-b2e6-92b364d9b262.png)

```
// package.json

"@gits-id/ui": "^0.10.12",
```

**Comment by gravitano** [comment]
Thank you for reporting the issue. We'll fix this ASAP.
