### ISSUE TITLE
[VTabs] Can't customize tab content without overriding internal rendering

### ISSUE THREAD

**Issue by gits-gretchelin** [gitsindonesia/ui-component#50]
I'm facing difficulties trying to minimally customize tab content in `VTabs`.

Currently, if I want to let's say, change the size of clickable area of the tab, I need to override the `v-tab` rendering in `v-tabs` through the default `slot` because the both `VTab` and `VTabs` component provide no way to customize the clickable wrapper. However, doing this means that I lose the built-in slider function that is built into v-tabs and I had to reinvent the wheel at least for the slider part.

It would be nice to either have the slider automatically detect custom tabs (if `v-tab` rendering is being overridden through slots), or expose a way for user to get the built-in slider to work with their custom tabs (ie. exposed onClick function maybe?).

**Comment by gravitano** [comment]
Try updating the package to version `0.13.8`. We can now customize the tabs via CSS Properties.
