### ISSUE TITLE
ui and nuxt export different version of NavDrawer

### ISSUE THREAD

**Issue by gits-gretchelin** [gitsindonesia/ui-component#72]
I recently have the opportunity to use the `ui` package and I found that some props doesn't work as expected while using `NavDrawer` from `@gits-id/ui` package. Meanwhile, in another project that uses the same component from `@gits-id/nuxt` with the same props applied, works as expected (per documentation and storybook example).

Diving into the code, it seems that these package export different version of `NavDrawer` as `VNavDrawer`.  Below are the export code in `ui` and `nuxt`:

https://github.com/gitsindonesia/ui-component/blob/cda5923c77eea564f1df3696753e7b21a5da97c5/packages/nuxt/src/module.ts#L266-L270

https://github.com/gitsindonesia/ui-component/blob/cda5923c77eea564f1df3696753e7b21a5da97c5/packages/ui/src/index.ts#L31

https://github.com/gitsindonesia/ui-component/blob/cda5923c77eea564f1df3696753e7b21a5da97c5/packages/ui/src/index.ts#L96

And this is how `NavDrawer` actually export its components
https://github.com/gitsindonesia/ui-component/blob/cda5923c77eea564f1df3696753e7b21a5da97c5/packages/nav-drawer/src/index.ts#L1-L3

> Based on the above findings, I assume that the reason why `NavDrawer` behave differently between `ui` and `nuxt` is because the one exported by `ui` is the `deprecated` one which by storybook example does not implement some props that currently exist in not-deprecated one.

**Comment by gravitano** [comment]
Hi. Yes it is intended for preventing breaking change. For older user will still use the `deprecated` version, while the new user like in the nuxt starter will use the new component.

**Comment by gits-gretchelin** [comment]
Okay, so it's advisable for newer user to export NavDrawer from `gits-id/nav-drawer` then? 

If so, maybe there should be a note in `ui` package, because the docs doesn't exactly have a page dedicated for the old version of NavDrawer nor point out which props are available from specific ver. onwards. Or, maybe in upgrade path or something. Just a section to tell how user can use the new version of certain components while waiting for new major ver. release to have this as default would be helpful.

**Comment by gravitano** [comment]
Yes. It's recommended to use the new `NavDrawer` component. The old one could be removed on the new major version.

```ts
import {NavDrawer} from '@gits-id/nav-drawer`;
```

I already document and add deprecation info on the old nav-drawer page: https://gitsindonesia.github.io/ui-component/components/nav-drawer.html

The new `NavDrawer` doc is here: https://gitsindonesia.github.io/ui-component/components/navigation-drawer.html

**Comment by gits-gretchelin** [comment]
My bad, somehow my eyes skipped that entry. Thanks for the link, I've read the deprecated one now. I know of the new one, but I guess my eyes glazed over when I see the deprecated ones.

I'll close this issue and remove the bug tag as it wasn't a bug.
