### ISSUE TITLE
VSelect -  the item list does not restore to the full list after clear selected item

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#95]
### Environment

- "nuxt": "3.0.0",
- "@gits-id/ui-nuxt": "^0.14.0",

### Reproduction

update gits-id/ui-nuxt to version 0.14.0
then yarn
and run project

### Describe the bug

after run project. here is my scenario
- open page contain VSelect with searchable feature
- input search item.  '1'
- click 'Item 1'
- selected item => 'Item 1'
checkpoint 1. its all green

second scenario i want to change selected item using search.
- before i start typing. i did click clear icon.
- item list opened
- search box already empty like below
<img width="522" alt="Screenshot 2023-01-10 at 16 55 43" src="https://user-images.githubusercontent.com/1776951/211519545-469e3ed6-bc79-42fa-9d82-228c9f0e14dc.png">

- and here is the **problem**. the item list not restore full, after i click icon clear

**Comment by gravitano** [comment]
Hi, sorry for the inconvenience. Would you mind creating full working reproduction via Stackblitz?

1. Visit https://stackblitz.com/github/gitsindonesia/ui-component/tree/main/starter/nuxt-minimal
2. Copy and paste the code to the `app.vue`
3. Run and paste the working stackblitz URL here

**Comment by karis** [comment]
yes, sure.

here is the link.

https://stackblitz.com/edit/github-ycbgbo?file=app.vue

**Comment by gravitano** [comment]
Hi @karis, I just released a new patch `0.14.1`. I think this issue is solved. Give it a try and report back if anything breaks.

You can also check out my forked version of your reproduction here: https://stackblitz.com/edit/github-ycbgbo-qxgzt3?file=package.json,app.vue

**Comment by karis** [comment]
hai @gravitano 

i've check, and it works fine,

i have another another story.
in real world. when user already type search..
and then Vselect display several suggest according to search text.
then user usually using keyboard("arrow down" = keypress code 40 or "arrow up" == keypress code 38)

i have tested it. items are not highlighted.
so i can only imagine, which item i will choose.

do i have to create another issue or we will keep this?


thanks 👍

**Comment by gravitano** [comment]
Currently, `VSelect` does not support keyboard navigation. Maybe would add it in the future. If you need to add keyboard navigation, you can use `VAutocomplete` or event create your own custom component using [Headless UI](https://headlessui.dev/).
